### ISSUE TITLE
How to see my db?

### ISSUE THREAD

**Issue by silentpride** [sjmelia/electron-boilerplate-sqlite#6]
Hi!
Sorry to bother you.
I just wonder how can i see the data in my sqlite3 ?

For example : 
var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');

Does it mean that I create a db named "memory" ?
In which file I can find it ?
And how can I see the data that I written in the DB ?

BTW, thanks for the answer on my last issues, it does works .

**Comment by sjmelia** [comment]
Hi there! It's outside the scope of this project to advise on the use of SQLite; you should take a look at the documentation for the npm package here: https://www.npmjs.com/package/sqlite3

That said - this bit of code creates an "in memory database" rather than persisting the file to disk; so you can't open any file to view it. You'll need to change the code to save data to a file; you can refer to the above docs and/or the documentation for SQLite to find out how to do this.

**Comment by silentpride** [comment]
Thanks a lot !
